export const SemanticMapping = {
  "gym": ["workout", "fitness", "exercise", "training", "Physical Health"],
  "workout": ["gym", "exercise", "training", "fitness", "strength"],
  "fitness": ["gym", "health", "exercise", "wellness", "physical activity"],
  "exercise": ["gym", "workout", "training", "movement", "physical activity"],
  "nutrition": ["diet", "food", "eating", "macros", "health"],
  "protein": ["muscle", "amino acids", "meat", "supplements", "recovery"],
  "carbohydrates": ["energy", "carbs", "sugar", "glucose", "fuel"],
  "fats": ["lipids", "oils", "energy", "healthy fats", "nutrition"],
  "bodybuilding": ["muscle", "strength", "hypertrophy", "gym", "training"],
  "calisthenics": ["bodyweight", "gymnastics", "strength", "movement", "fitness"],
  "bouldering": ["climbing", "grip", "strength", "technique", "problem-solving"],
  "art": ["drawing", "sketching", "creativity", "technique", "expression"],
  "cooking": ["food", "recipes", "nutrition", "meal prep", "kitchen"],
  "strength": ["power", "muscle", "force", "resistance", "training"],
  "technique": ["form", "skill", "method", "practice", "execution"],
  "recovery": ["rest", "sleep", "healing", "regeneration", "restoration"],
  "progression": ["improvement", "advancement", "growth", "development", "evolution"],
  "form": ["technique", "posture", "alignment", "execution", "movement"],
  "core": ["abs", "stability", "strength", "balance", "center"],
  "grip": ["hold", "strength", "forearm", "climbing", "control"],
  "balance": ["stability", "coordination", "control", "equilibrium", "core"],
  "flexibility": ["mobility", "range of motion", "stretching", "suppleness", "movement"],
  "endurance": ["stamina", "persistence", "resilience", "durability", "sustainability"],
  "mindset": ["attitude", "psychology", "focus", "determination", "mental game"],
  "safety": ["prevention", "protection", "caution", "awareness", "well-being"],
  "equipment": ["tools", "gear", "machines", "devices", "apparatus"]
};